<div x-data="{ edificioModal: false, edificioId: @js(old('id_edificio', $linea->id_edificio ?? '')), edificioNombre: @js(old('id_edificio') ? optional($edificios->firstWhere('id_edificio', old('id_edificio')))->nombre : ($linea->edificio->nombre ?? '')) }" class="rounded-2xl border border-gray-700 bg-gray-800 p-6 shadow-xl">
    <h3 class="text-lg font-semibold text-white">{{ $title }}</h3>
    <form method="POST" action="{{ $action }}" class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2">
        @csrf @if ($method !== 'POST') @method($method) @endif
        <input type="hidden" name="id_edificio" :value="edificioId">
        <div class="md:col-span-2"><label class="mb-1 block text-sm text-gray-300">Edificio</label><button @click="edificioModal = true" type="button" class="flex w-full items-center justify-between rounded-lg border border-gray-700 bg-gray-900 px-3 py-2 text-left text-white"><span x-text="edificioNombre || 'Seleccionar edificio'"></span><i class="ri-building-2-line text-cyan-400"></i></button>@error('id_edificio')<span class="text-sm text-red-400">{{ $message }}</span>@enderror</div>
        <div><label for="proveedor" class="mb-1 block text-sm text-gray-300">Proveedor</label><select id="proveedor" name="proveedor" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"><option value="">Seleccionar</option>@foreach(['Telmex', 'Izzi', 'MegaCable', 'totalPal', 'Starlink', 'Cable', 'Sky', 'Otros'] as $proveedor)<option value="{{ $proveedor }}" @selected(old('proveedor', $linea->proveedor ?? '') === $proveedor)>{{ $proveedor }}</option>@endforeach</select>@error('proveedor')<span class="text-sm text-red-400">{{ $message }}</span>@enderror</div>
        <div><label for="numero_contrato" class="mb-1 block text-sm text-gray-300">Número de contrato</label><input id="numero_contrato" name="numero_contrato" value="{{ old('numero_contrato', $linea->numero_contrato ?? '') }}" maxlength="50" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@error('numero_contrato')<span class="text-sm text-red-400">{{ $message }}</span>@enderror</div>
        <div><label for="numero_telefono" class="mb-1 block text-sm text-gray-300">Teléfono</label><input id="numero_telefono" name="numero_telefono" value="{{ old('numero_telefono', $linea->numero_telefono ?? '') }}" maxlength="20" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
        <div><label for="ubicacion_especifica" class="mb-1 block text-sm text-gray-300">Ubicación específica</label><input id="ubicacion_especifica" name="ubicacion_especifica" value="{{ old('ubicacion_especifica', $linea->ubicacion_especifica ?? '') }}" maxlength="150" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
        <div><label for="modelo_modem" class="mb-1 block text-sm text-gray-300">Modelo de módem</label><input id="modelo_modem" name="modelo_modem" value="{{ old('modelo_modem', $linea->modelo_modem ?? '') }}" maxlength="100" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
        <div><label for="ip_publica" class="mb-1 block text-sm text-gray-300">IP pública</label><input id="ip_publica" name="ip_publica" value="{{ old('ip_publica', $linea->ip_publica ?? '') }}" maxlength="45" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@error('ip_publica')<span class="text-sm text-red-400">{{ $message }}</span>@enderror</div>
        <div><label for="estatus_linea" class="mb-1 block text-sm text-gray-300">Estatus</label><select id="estatus_linea" name="estatus_linea" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@foreach(['Activa', 'Inactiva', 'En_revision'] as $estatus)<option value="{{ $estatus }}" @selected(old('estatus_linea', $linea->estatus_linea ?? 'Activa') === $estatus)>{{ str_replace('_', ' ', $estatus) }}</option>@endforeach</select></div>
        <div class="md:col-span-2"><label for="observaciones" class="mb-1 block text-sm text-gray-300">Observaciones</label><textarea id="observaciones" name="observaciones" rows="3" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">{{ old('observaciones', $linea->observaciones ?? '') }}</textarea></div>
        <div class="flex justify-end gap-3 md:col-span-2"><a href="{{ route('lineas-internet.index') }}" class="rounded-lg border border-gray-600 px-4 py-2 text-sm text-gray-300 hover:bg-gray-700">Cancelar</a><button type="submit" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700">Guardar</button></div>
    </form>
    <div x-show="edificioModal" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4" role="dialog" aria-modal="true"><div @click.outside="edificioModal = false" class="w-full max-w-lg rounded-2xl border border-gray-700 bg-gray-800 p-6 shadow-2xl"><div class="flex items-center justify-between"><h3 class="text-lg font-semibold text-white">Seleccionar edificio</h3><button @click="edificioModal = false" type="button" class="text-gray-400 hover:text-white" title="Cerrar"><x-lucide name="x" class="h-5 w-5" /></button></div><div class="mt-4 max-h-80 space-y-2 overflow-y-auto">@forelse($edificios as $edificio)<button @click="edificioId = '{{ $edificio->id_edificio }}'; edificioNombre = @js($edificio->nombre); edificioModal = false" type="button" class="block w-full rounded-lg border border-gray-700 bg-gray-900 px-4 py-3 text-left text-white hover:border-cyan-500 hover:bg-gray-700">{{ $edificio->nombre }}<span class="block text-xs text-gray-400">{{ $edificio->direccion ?: 'Sin dirección' }}</span></button>@empty<p class="text-sm text-gray-400">No hay edificios registrados.</p>@endforelse</div></div></div>
</div>