<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-100 flex items-center gap-2"><i class="ri-router-line"></i>{{ __('Líneas de Internet') }}</h2></x-slot>
    <div class="py-6"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if (session('message')) <div class="mb-4 rounded-lg border border-green-700 bg-green-900/40 px-4 py-3 text-green-200">{{ session('message') }}</div> @endif
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-white">Líneas de Internet</h2><p class="text-sm text-gray-400">Administra las conexiones y su edificio asociado.</p></div><a href="{{ route('lineas-internet.create') }}" class="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"><x-lucide name="plus" class="h-4 w-4" />Nueva línea</a></div>
        <div class="rounded-2xl border border-gray-700 bg-gray-800 p-5 shadow-xl">
            <form method="GET" action="{{ route('lineas-internet.index') }}"><input name="search" value="{{ request('search') }}" type="search" placeholder="Buscar por edificio, contrato, teléfono o IP..." class="w-full rounded-lg border-gray-700 bg-gray-900 text-white placeholder-gray-500 focus:border-blue-500 focus:ring-blue-500"></form>
            <div class="mt-5 overflow-x-auto"><table class="min-w-full divide-y divide-gray-700"><thead><tr class="text-left text-xs uppercase tracking-wider text-gray-400"><th class="px-4 py-3">Edificio</th><th class="px-4 py-3">Proveedor</th><th class="px-4 py-3">Contrato</th><th class="px-4 py-3">IP pública</th><th class="px-4 py-3">Estado</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-gray-700 text-sm text-gray-200">
                @forelse ($lineas as $linea)<tr class="hover:bg-gray-700/40"><td class="px-4 py-3 font-medium text-white">{{ $linea->edificio->nombre }}</td><td class="px-4 py-3">{{ $linea->proveedor }}</td><td class="px-4 py-3">{{ $linea->numero_contrato }}</td><td class="px-4 py-3">{{ $linea->ip_publica ?: 'Sin IP' }}</td><td class="px-4 py-3">{{ str_replace('_', ' ', $linea->estatus_linea) }}</td><td class="px-4 py-3 text-right"><a href="{{ route('lineas-internet.edit', $linea) }}" class="mr-3 text-blue-400 hover:text-blue-300" title="Editar"><x-lucide name="pencil" class="inline h-4 w-4" /></a><form method="POST" action="{{ route('lineas-internet.destroy', $linea) }}" class="inline" onsubmit="return confirm('¿Deseas eliminar esta línea?')">@csrf @method('DELETE')<button type="submit" class="text-red-400 hover:text-red-300" title="Eliminar"><x-lucide name="trash-2" class="inline h-4 w-4" /></button></form></td></tr>
                @empty <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">No hay líneas de internet registradas.</td></tr> @endforelse
            </tbody></table></div><div class="mt-4">{{ $lineas->links() }}</div>
        </div>
    </div></div>
</x-app-layout>