<div class="rounded-2xl border border-gray-700 bg-gray-800 p-6 shadow-xl"><h3 class="text-lg font-semibold text-white">{{ $title }}</h3><form method="POST" action="{{ $action }}" class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2">@csrf @if($method !== 'POST')@method($method)@endif
    <div class="md:col-span-2"><label for="id_linea" class="mb-1 block text-sm text-gray-300">Línea de internet</label><select id="id_linea" name="id_linea" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"><option value="">Seleccionar línea</option>@foreach($lineas as $linea)<option value="{{ $linea->id_linea }}" @selected((string)old('id_linea', $reporte->id_linea ?? '') === (string)$linea->id_linea)>{{ $linea->edificio->nombre }} - {{ $linea->numero_contrato }} ({{ $linea->proveedor }})</option>@endforeach</select>@error('id_linea')<span class="text-sm text-red-400">{{ $message }}</span>@enderror</div>
    <div><label for="folio_ticket_proveedor" class="mb-1 block text-sm text-gray-300">Folio del proveedor</label><input id="folio_ticket_proveedor" name="folio_ticket_proveedor" value="{{ old('folio_ticket_proveedor', $reporte->folio_ticket_proveedor ?? '') }}" maxlength="50" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
    <div><label for="tipo_falla" class="mb-1 block text-sm text-gray-300">Tipo de falla</label><select id="tipo_falla" name="tipo_falla" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@foreach(['Sin_servicio','Intermitencia','Lentitud','Falla_hardware','Otro'] as $tipo)<option value="{{ $tipo }}" @selected(old('tipo_falla', $reporte->tipo_falla ?? '') === $tipo)>{{ str_replace('_', ' ', $tipo) }}</option>@endforeach</select></div>
    <div><label for="prioridad" class="mb-1 block text-sm text-gray-300">Prioridad</label><select id="prioridad" name="prioridad" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@foreach(['Baja','Media','Alta','Critica'] as $valor)<option value="{{ $valor }}" @selected(old('prioridad', $reporte->prioridad ?? 'Media') === $valor)>{{ $valor }}</option>@endforeach</select></div>
    <div><label for="estatus" class="mb-1 block text-sm text-gray-300">Estatus</label><select id="estatus" name="estatus" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">@foreach(['Abierto','En_proceso','Escalado','Resuelto','Cerrado'] as $valor)<option value="{{ $valor }}" @selected(old('estatus', $reporte->estatus ?? 'Abierto') === $valor)>{{ str_replace('_', ' ', $valor) }}</option>@endforeach</select></div>
    <div><label for="fecha_apertura" class="mb-1 block text-sm text-gray-300">Fecha de apertura</label><input id="fecha_apertura" name="fecha_apertura" type="datetime-local" value="{{ old('fecha_apertura', isset($reporte) ? $reporte->fecha_apertura?->format('Y-m-d\\TH:i') : now()->format('Y-m-d\\TH:i')) }}" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
    <div><label for="fecha_cierre" class="mb-1 block text-sm text-gray-300">Fecha de cierre</label><input id="fecha_cierre" name="fecha_cierre" type="datetime-local" value="{{ old('fecha_cierre', isset($reporte) && $reporte->fecha_cierre ? $reporte->fecha_cierre->format('Y-m-d\\TH:i') : '') }}" class="w-full rounded-lg border-gray-700 bg-gray-900 text-white"></div>
    <div class="md:col-span-2"><label for="descripcion_problema" class="mb-1 block text-sm text-gray-300">Descripción del problema</label><textarea id="descripcion_problema" name="descripcion_problema" rows="4" required class="w-full rounded-lg border-gray-700 bg-gray-900 text-white">{{ old('descripcion_problema', $reporte->descripcion_problema ?? '') }}</textarea></div>
    <div class="flex justify-end gap-3 md:col-span-2"><a href="{{ route('reportes-incidentes.index') }}" class="rounded-lg border border-gray-600 px-4 py-2 text-sm text-gray-300 hover:bg-gray-700">Cancelar</a><button type="submit" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700">Guardar</button></div>
</form></div>