<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-100 flex items-center gap-2"><i class="ri-alarm-warning-line"></i>Reportes de Incidentes</h2></x-slot>
    <div class="py-6"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if (session('message'))<div class="mb-4 rounded-lg border border-green-700 bg-green-900/40 px-4 py-3 text-green-200">{{ session('message') }}</div>@endif
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-white">Reportes de Incidentes</h2><p class="text-sm text-gray-400">Registra fallas de red y consulta su seguimiento.</p></div><a href="{{ route('reportes-incidentes.create') }}" class="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"><x-lucide name="plus" class="h-4 w-4" />Nuevo reporte</a></div>
        <div class="rounded-2xl border border-gray-700 bg-gray-800 p-5 shadow-xl"><form method="GET"><input name="search" value="{{ request('search') }}" type="search" placeholder="Buscar por folio, edificio o descripción..." class="w-full rounded-lg border-gray-700 bg-gray-900 text-white placeholder-gray-500 focus:border-blue-500 focus:ring-blue-500"></form>
            <div class="mt-5 overflow-x-auto"><table class="min-w-full divide-y divide-gray-700"><thead><tr class="text-left text-xs uppercase tracking-wider text-gray-400"><th class="px-4 py-3">Edificio / línea</th><th class="px-4 py-3">Falla</th><th class="px-4 py-3">Prioridad</th><th class="px-4 py-3">Estatus</th><th class="px-4 py-3">Seguimientos</th><th class="px-4 py-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-gray-700 text-sm text-gray-200">
                @forelse($reportes as $reporte)<tr class="hover:bg-gray-700/40"><td class="px-4 py-3"><span class="font-medium text-white">{{ $reporte->linea->edificio->nombre }}</span><span class="block text-xs text-gray-400">Contrato: {{ $reporte->linea->numero_contrato }}</span></td><td class="px-4 py-3">{{ str_replace('_', ' ', $reporte->tipo_falla) }}</td><td class="px-4 py-3">{{ $reporte->prioridad }}</td><td class="px-4 py-3">{{ str_replace('_', ' ', $reporte->estatus) }}</td><td class="px-4 py-3">{{ $reporte->seguimientos_count }}</td><td class="px-4 py-3 text-right"><a href="{{ route('reportes-incidentes.show', $reporte) }}" class="mr-3 text-cyan-400 hover:text-cyan-300" title="Ver"><x-lucide name="eye" class="inline h-4 w-4" /></a><a href="{{ route('reportes-incidentes.edit', $reporte) }}" class="text-blue-400 hover:text-blue-300" title="Editar"><x-lucide name="pencil" class="inline h-4 w-4" /></a></td></tr>
                @empty<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">No hay reportes de incidentes registrados.</td></tr>@endforelse
            </tbody></table></div><div class="mt-4">{{ $reportes->links() }}</div>
        </div>
    </div></div>
</x-app-layout>